config/routes.rb
Workspace::Application.routes.draw do

  get 'posts/new' => 'posts#new'
  get "posts" => 'posts#index'
  get "posts/:id" => 'posts#show', as: 'post_show'
  post 'posts' => 'posts#create'
  resources :users do
    member do
      get 'edit_role' => 'users#edit_role'
      post 'add_role' => 'users#add_role'
    end
    collection do
      get 'list_active' => 'users#list_active'
    end
  end
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy', as: :sign_out
  
  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A\S+@\S+\.\S+\z/, message: 'invalid format' }

    mount_uploader :file, FileUploader
    
    has_secure_password
    
    has_many :cats
    
    has_and_belongs_to_many :roles
    
    accepts_nested_attributes_for :cats, allow_destroy: true
    
    accepts_nested_attributes_for :roles, allow_destroy: true
    
    def add_role(role_name)
      role = Role.where(name: role_name).first
      if role && !self.roles.include?(role)
          self.roles.push(role)
      end
    end
    
    def remove_role(role_name)

       role = Role.where(name: role_name).first
        if role && self.roles.include?(role)
           self.roles.delete(role) 
        end
    end
    
    def has_role?(role_name)
       self.roles.include?(Role.where(name: role_name).first) 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  #before_filter :verify_admin, only: [:index]
  load_and_authorize_resource
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      #UserMailer.welcome_email(@user).deliver
      redirect_to user_path(id: @user.id), notice: "Successfully Signed Up"
    else

      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    
    # if @user.cats.count == 0
    #   @user.cats.build
    # end
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to user_path(id: @user.id), notice: 'Successfully Updated User'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    
    if @user.destroy
      redirect_to users_path, notice: 'Successfully deleted User'
    else
      render :index
    end
  end
  
  def edit_role
    @user = User.find(params[:id])
  end
  
  def add_role
    @user = User.find(params[:id])
    role_change_messages = ""
    roles = params[:user][:roles_attributes]
    roles.each do |key,role|
      if role['_destroy'] == "1"
        @user.remove_role(role['name'])
        role_change_messages += "Removed Role #{role['name']}. "
      else
        @user.add_role(role['name'])
        
        role_change_messages += "Added Role #{role['name']}. "
      end
    end
    redirect_to :back, notice: role_change_messages

  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :file, :file_cache, :remove_file, cats_attributes: [:id, :name, :colour, :_destroy])
  end
  
  def verify_admin
    if user_logged_in?
      if !current_user.has_role?('Admin')
        redirect_to (request.referrer || root_path), notice: 'You need to be admin to view that page'
      end
    else
      redirect_to (request.referrer || root_path), notice: 'You need to be admin to view that page'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= nested_form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
     
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <%= image_tag(@user.file_url) if @user.file? %>
          <span class="input-group-addon"><%= f.label "Upload a Photo" %></span>
          <%= f.file_field :file, class: "form-control" %>
          <%= f.hidden_field :file_cache %>
          <label>
            <%= f.check_box :remove_file %>
            Remove file
          </label>
        </div>        
    </div>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :name %></span>
          <%= f.text_field :name, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :email %></span>
          <%= f.text_field :email, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :password %></span>
          <%= f.password_field :password, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :password_confirmation %></span>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
        <h3>This guy's Cat:</h3>
        <%= f.fields_for :cats do |cat| %>
          <div class="input-group col-xs-6">
            <span class="input-group-addon"><%= cat.label :name %></span>
            <%= cat.text_field :name, class: "form-control" %>
          </div>  
          <div class="input-group col-xs-6">
            <span class="input-group-addon"><%= cat.label :colour %></span>
            <%= cat.text_field :colour, class: "form-control" %>
          </div> 
          <%= cat.link_to_remove "Remove this cat" %>
        <% end %>
     
        <p><%= f.link_to_add "Add a cat", :cats %></p>
    </div>    
    <div class="row">
        <div class="input-group col-xs-6">
          <%= f.submit class: "btn btn-default" %>
        </div>             
    </div>
<% end %>    

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Editing User <%=@user.name %></h1>
        <%= render 'form' %> 
    </div>
   
</div>

app/views/users/edit_role.html.erb
<%= nested_form_for @user , url: add_role_user_path, method: :post do |f| %>
    <h1>Add Role to <%= @user.name %></h1>
    <%= f.fields_for :roles do |role| %>
        <%= role.label 'Role Name' %>
        <%= role.text_field :name %>
         <%= role.link_to_remove "Remove this role" %>
    <% end %>
    
    <p><%= f.link_to_add "Add a role", :roles %></p>
    <%= f.submit %>
<% end %>

Params:
<%= params %>
<%= @roles %>

app/views/users/index.html.erb
<h1>User list</h1>

<ul>
    <% @users.each do |user| %>
        <li><span><%= link_to user.name, edit_user_path(id: user.id) %></span>&nbsp;&nbsp;&nbsp;<span><%= link_to 'Delete', user_path(id: user.id), method: :delete, confirm: 'Are you sure you want to delete this user?' %></span></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Register Now!</h1>
        <%= render 'form' %> 
    </div>
   
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3>Details</h3>
<% if @user.file? %>
<%= image_tag(@user.file_url) %>
<% end %>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

<% if @user.cats.count > 0 %>
    <h3>This guy's Cat's details</h3>
    <ul>
        <% @user.cats.each do |cat| %>
            <li>
                <p><%= cat.name %>, which is <%= cat.colour %> in colour.</p>
            </li>
        <% end %> 
    </ul>

<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>