config/routes.rb
Workspace::Application.routes.draw do

  get 'posts/new' => 'posts#new'
  get "posts" => 'posts#index'
  get "posts/:id" => 'posts#show', as: 'post_show'
  post 'posts' => 'posts#create'
  resources :users do
    member do
      get 'edit_role' => 'users#edit_role'
      post 'add_role' => 'users#add_role'
    end
    collection do
      get 'list_active' => 'users#list_active'
    end
  end
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy', as: :sign_out
  
  root 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class='col-xs-4'>
      <h1>Whatimeisit</h1>
    </div>
    <div class='col-xs-4 col-xs-offset-4'>
      <% if user_logged_in? %>
        <%= link_to 'Sign Out', sign_out_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to 'Sign In', sign_in_path %>
      <% end%>
      <%= link_to 'List Users', users_path %>
    </div>

  </div>
</nav>
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>